data<-read.delim("C:/Users/Alex/Downloads/r_programming_data/household_power_consumption.txt", header=TRUE,sep=";", na.strings="?")
mydata2<-subset(data, Date=='2/2/2007')
mydata1<-subset(data,Date=='1/2/2007')
rmydata<-rbind(mydata1, mydata2)
as.date.data<-as.Date(data$Date, format="%d/%m/%Y")
rmydata$DateTime <- as.POSIXct(paste(rmydata$Date, rmydata$Time), format="%d/%m/%Y %H:%M:%S")
hist(rmydata$Global_active_power, xlab="Global Active Power (kilowatts)", col="red", main="Global Active Power")

png(filename = "Plot1.png",width = 480, height = 480, units = "px")
hist(rmydata$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red")
dev.off()